/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Default Settings */
        get: operations["get_default_settings_api_settings_default_get"];
        /** Put Default Settings */
        put: operations["put_default_settings_api_settings_default_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default/sync-provider-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Provider Preview */
        post: operations["sync_provider_preview_api_settings_default_sync_provider_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default/test-embedding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Embedding Settings */
        post: operations["test_embedding_settings_api_settings_default_test_embedding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default/test-llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Llm Settings */
        post: operations["test_llm_settings_api_settings_default_test_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default/test-reranker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Reranker Settings */
        post: operations["test_reranker_settings_api_settings_default_test_reranker_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/default/test-mineru": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Mineru Settings */
        post: operations["test_mineru_settings_api_settings_default_test_mineru_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Variants */
        get: operations["list_variants_api_variants_get"];
        put?: never;
        /** Create Variant */
        post: operations["create_variant_api_variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Variant */
        get: operations["get_variant_api_variants__variant_id__get"];
        /** Update Variant */
        put: operations["update_variant_api_variants__variant_id__put"];
        post?: never;
        /** Delete Variant */
        delete: operations["delete_variant_api_variants__variant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Document */
        post: operations["reindex_document_api_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/graph/rematerialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rematerialize Document Graph */
        post: operations["rematerialize_document_graph_api_documents__document_id__graph_rematerialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domain-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Domain Profiles */
        get: operations["list_domain_profiles_api_domain_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domain-profiles/reference-json-example": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reference Json Example */
        get: operations["get_reference_json_example_api_domain_profiles_reference_json_example_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domain-profiles/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Domain Metadata */
        post: operations["suggest_domain_metadata_api_domain_profiles_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domain-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Domain Profile */
        put: operations["upsert_domain_profile_api_domain_profiles__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Chunks */
        post: operations["search_chunks_api_chunks_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/quality-warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Quality Warnings */
        get: operations["job_quality_warnings_api_jobs__job_id__quality_warnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/quality-warnings/fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fix Job Quality Warnings */
        post: operations["fix_job_quality_warnings_api_jobs__job_id__quality_warnings_fix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation-sets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Evaluation Set */
        post: operations["import_evaluation_set_api_evaluation_sets_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluation Sets */
        get: operations["list_evaluation_sets_api_evaluation_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimizer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_api_optimizer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimizer/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend For Experiment */
        post: operations["recommend_for_experiment_api_optimizer__experiment_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostics */
        get: operations["get_diagnostics_api_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_evaluation_set_api_evaluation_sets_import_post */
        Body_import_evaluation_set_api_evaluation_sets_import_post: {
            /** File */
            file: string;
        };
        /** Body_suggest_domain_metadata_api_domain_profiles_suggest_post */
        Body_suggest_domain_metadata_api_domain_profiles_suggest_post: {
            /** File */
            file: string;
            /** Profile Id */
            profile_id?: string | null;
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /** File */
            file: string;
            /** Parser Mode */
            parser_mode?: string | null;
            /** Domain Metadata */
            domain_metadata?: string | null;
            /** Mineru Parse Options */
            mineru_parse_options?: string | null;
        };
        /** ChunkOut */
        ChunkOut: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
            /** Source Location */
            source_location: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Runtime Profile Id */
            runtime_profile_id?: string | null;
            /** Runtime Source Id */
            runtime_source_id?: string | null;
            /**
             * Content Type
             * @default text
             */
            content_type: string;
            /** Preview Ref */
            preview_ref?: string | null;
            /** Indexed At */
            indexed_at?: string | null;
            /** Retrieval Explain */
            retrieval_explain?: {
                [key: string]: unknown;
            } | null;
            /** Relationship Refs */
            relationship_refs?: {
                [key: string]: string;
            };
        };
        /** ChunkSearchIn */
        ChunkSearchIn: {
            /** Query */
            query: string;
            /**
             * Document Ids
             * @default []
             */
            document_ids: string[];
            /** Variant Id */
            variant_id?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Explain
             * @default true
             */
            explain: boolean;
            /**
             * Include Neighbors
             * @default true
             */
            include_neighbors: boolean;
        };
        /** ChunkSearchOut */
        ChunkSearchOut: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Total */
            total: number;
        };
        /** DiagnosticsOut */
        DiagnosticsOut: {
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Dependency Status */
            dependency_status: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
            /**
             * Runtime Mode
             * @default runtime
             */
            runtime_mode: string;
            /**
             * Overall Status
             * @default failed
             * @enum {string}
             */
            overall_status: "ready" | "degraded" | "failed";
            /** Checks */
            checks?: components["schemas"]["RuntimeHealthCheck"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Sha256 */
            sha256: string;
            status: components["schemas"]["StageStatus"];
            latest_index_options?: components["schemas"]["IndexDocumentIn"] | null;
        };
        /** DomainMetadata */
        DomainMetadata: {
            /**
             * Domain
             * @default generic
             */
            domain: string;
            /**
             * Document Type
             * @default document
             */
            document_type: string;
            /**
             * Language
             * @default unknown
             */
            language: string;
            /** Tags */
            tags?: string[];
            /** Authority */
            authority?: string | null;
            /** Source */
            source?: string | null;
            /** Collection */
            collection?: string | null;
            /** Citation Style */
            citation_style?: string | null;
            /** Expected Structure */
            expected_structure?: string | null;
            /** Custom Json */
            custom_json?: {
                [key: string]: unknown;
            };
            /** Reference Pattern */
            reference_pattern?: string | null;
            /** Script */
            script?: string | null;
            /** Content Role */
            content_role?: string | null;
            /** Metadata Sources */
            metadata_sources?: string[];
        };
        /** DomainMetadataSuggestOut */
        DomainMetadataSuggestOut: {
            domain_metadata: components["schemas"]["DomainMetadata"];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Evidence Pages */
            evidence_pages?: number[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Warnings */
            warnings?: string[];
        };
        /** DomainProfileIn */
        DomainProfileIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            metadata: components["schemas"]["DomainMetadata"];
        };
        /** DomainProfileListOut */
        DomainProfileListOut: {
            /** Items */
            items: components["schemas"]["DomainProfileOut"][];
            /** Total */
            total: number;
        };
        /** DomainProfileOut */
        DomainProfileOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            metadata: components["schemas"]["DomainMetadata"];
        };
        /** EmbeddingConnectionTestOut */
        EmbeddingConnectionTestOut: {
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: number | null;
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail: string;
        };
        /** EvaluationCaseIn */
        EvaluationCaseIn: {
            /** Id */
            id: string;
            /** Query */
            query: string;
            /**
             * Documents
             * @default []
             */
            documents: string[];
            /** Expected Answer */
            expected_answer?: string | null;
            /**
             * Expected Sources
             * @default []
             */
            expected_sources: string[];
            /**
             * Must Include
             * @default []
             */
            must_include: string[];
            /**
             * Must Avoid
             * @default []
             */
            must_avoid: string[];
            /**
             * Expected Media
             * @default []
             */
            expected_media: {
                [key: string]: unknown;
            }[];
            /**
             * Expected Structure
             * @default {}
             */
            expected_structure: {
                [key: string]: unknown;
            };
            /**
             * Rubric
             * @default {}
             */
            rubric: {
                [key: string]: string;
            };
            /**
             * Objective
             * @default {}
             */
            objective: {
                [key: string]: unknown;
            };
            /**
             * Variant Hints
             * @default {}
             */
            variant_hints: {
                [key: string]: string[];
            };
        };
        /** EvaluationSetOut */
        EvaluationSetOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Cases */
            cases: components["schemas"]["EvaluationCaseIn"][];
        };
        /** EvaluationSetPage */
        EvaluationSetPage: {
            /** Items */
            items: components["schemas"]["EvaluationSetOut"][];
            /** Total */
            total: number;
        };
        /** ExperimentIn */
        ExperimentIn: {
            /** Name */
            name: string;
            /** Document Ids */
            document_ids: string[];
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Variant Ids */
            variant_ids: string[];
            /** Objective */
            objective: {
                [key: string]: unknown;
            };
        };
        /** ExperimentOut */
        ExperimentOut: {
            /** Name */
            name: string;
            /** Document Ids */
            document_ids: string[];
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Variant Ids */
            variant_ids: string[];
            /** Objective */
            objective: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Runs
             * @default []
             */
            runs: components["schemas"]["RunOut"][];
            /**
             * Scores
             * @default []
             */
            scores: components["schemas"]["ExperimentScoreOut"][];
        };
        /** ExperimentPage */
        ExperimentPage: {
            /** Items */
            items: components["schemas"]["ExperimentSummaryOut"][];
            /** Total */
            total: number;
        };
        /** ExperimentScoreOut */
        ExperimentScoreOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Total */
            total: number;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ExperimentSummaryOut */
        ExperimentSummaryOut: {
            /** Name */
            name: string;
            /** Document Ids */
            document_ids: string[];
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Variant Ids */
            variant_ids: string[];
            /** Objective */
            objective: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Run Count
             * @default 0
             */
            run_count: number;
            /**
             * Score Count
             * @default 0
             */
            score_count: number;
        };
        /** GraphOut */
        GraphOut: {
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
            /** Edges */
            edges: {
                [key: string]: unknown;
            }[];
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexDocumentIn */
        IndexDocumentIn: {
            /**
             * Parser Mode
             * @default mineru_strict
             * @constant
             */
            parser_mode: "mineru_strict";
            domain_metadata?: components["schemas"]["DomainMetadata"];
            mineru_parse_options?: components["schemas"]["MinerUParseOptionsIn"] | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            status: components["schemas"]["StageStatus"];
            /** Target Id */
            target_id: string | null;
            /** Progress */
            progress: number;
            /** Logs */
            logs: string[];
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Worker Id */
            worker_id: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Recovery Action */
            recovery_action: string | null;
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Total */
            total: number;
        };
        /** JobQualityWarningRepairOut */
        JobQualityWarningRepairOut: {
            /** Source Job Id */
            source_job_id: string;
            /** Document Id */
            document_id: string;
            /** Queued Job Id */
            queued_job_id: string;
            queued_job_status: components["schemas"]["StageStatus"];
            /** Index Options */
            index_options: {
                [key: string]: unknown;
            };
            /** Repair Plan */
            repair_plan: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** JobQualityWarningsOut */
        JobQualityWarningsOut: {
            /** Job Id */
            job_id: string;
            /** Document Id */
            document_id: string | null;
            /** Parser Quality */
            parser_quality: {
                [key: string]: unknown;
            };
            /** Index Quality Report */
            index_quality_report?: {
                [key: string]: unknown;
            } | null;
            /** Job Warnings */
            job_warnings: string[];
            /** Warning Counts */
            warning_counts: {
                [key: string]: number;
            };
            /** Affected Chunks */
            affected_chunks: number;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Truncated */
            truncated: boolean;
            /** Items */
            items: components["schemas"]["ParserQualityWarningOut"][];
        };
        /** LlmConnectionTestOut */
        LlmConnectionTestOut: {
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail: string;
        };
        /** MinerUConnectionTestOut */
        MinerUConnectionTestOut: {
            /** Ok */
            ok: boolean;
            /** Base Url */
            base_url: string;
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail: string;
            optimization?: components["schemas"]["MinerUOptimizationOut"];
        };
        /** MinerUOptimizationOut */
        MinerUOptimizationOut: {
            /** Requested */
            requested?: {
                [key: string]: unknown;
            };
            /** Reported */
            reported?: {
                [key: string]: unknown;
            };
            /**
             * Capacity Reported
             * @default false
             */
            capacity_reported: boolean;
            /** Warning */
            warning?: string | null;
        };
        /** MinerUParseOptionsIn */
        MinerUParseOptionsIn: {
            /** Parser */
            parser?: string | null;
            /** Parse Method */
            parse_method?: string | null;
            /** Backend */
            backend?: string | null;
            /** Device */
            device?: string | null;
            /** Lang */
            lang?: string | null;
            /** Formula */
            formula?: boolean | null;
            /** Table */
            table?: boolean | null;
            /** Source */
            source?: string | null;
            /** Max Concurrent Files */
            max_concurrent_files?: number | null;
        };
        /** OptimizerCandidateSummary */
        OptimizerCandidateSummary: {
            /** Variant Id */
            variant_id: string;
            /** Run Count */
            run_count: number;
            /** Average Score */
            average_score: number | null;
            /** Total Score */
            total_score: number | null;
            /** Best Run Id */
            best_run_id: string | null;
            /** Best Run Score */
            best_run_score: number | null;
            /**
             * Score Status
             * @default unscored
             */
            score_status: string;
            /**
             * Scoreable Run Count
             * @default 0
             */
            scoreable_run_count: number;
            /**
             * Unscored Run Count
             * @default 0
             */
            unscored_run_count: number;
            /**
             * Failed Run Count
             * @default 0
             */
            failed_run_count: number;
        };
        /** OptimizerIn */
        OptimizerIn: {
            /** Experiment Id */
            experiment_id: string;
            /** Objective */
            objective?: {
                [key: string]: unknown;
            };
        };
        /** OptimizerOut */
        OptimizerOut: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Objective */
            objective: {
                [key: string]: unknown;
            };
            /** Selected Variant Id */
            selected_variant_id: string | null;
            /** Selected Run Id */
            selected_run_id: string | null;
            /** Explanation */
            explanation: string;
            /** Tried Variant Ids */
            tried_variant_ids: string[];
            /**
             * Candidate Summaries
             * @default []
             */
            candidate_summaries: components["schemas"]["OptimizerCandidateSummary"][];
        };
        /** ParserQualityWarningOut */
        ParserQualityWarningOut: {
            /** Chunk Id */
            chunk_id: string;
            /** Chunk Preview */
            chunk_preview: string;
            /** Source Location */
            source_location: {
                [key: string]: unknown;
            };
            /** Parser Metadata */
            parser_metadata: {
                [key: string]: unknown;
            };
            /** Reference Metadata */
            reference_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Code */
            code?: string | null;
            /** Message */
            message?: string | null;
            /** Block Type */
            block_type?: string | null;
            /** Page */
            page?: number | string | null;
            /** Warning */
            warning: {
                [key: string]: unknown;
            };
        };
        /** ProviderSyncPreviewIn */
        ProviderSyncPreviewIn: {
            /** Manifest Url */
            manifest_url: string;
        };
        /** ProviderSyncPreviewOut */
        ProviderSyncPreviewOut: {
            /** Ok */
            ok: boolean;
            /** Manifest Url */
            manifest_url: string;
            /** Manifest Version */
            manifest_version?: number | null;
            /** Updated At */
            updated_at?: string | null;
            /** Patch */
            patch: {
                [key: string]: unknown;
            };
            /** Changed Fields */
            changed_fields: string[];
            /** Ignored Sections */
            ignored_sections: string[];
            /** Detail */
            detail: string;
        };
        /** QueryIn */
        QueryIn: {
            /** Query */
            query: string;
            /** Document Ids */
            document_ids?: string[];
            /** Variant Ids */
            variant_ids: string[];
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Response Mode
             * @default fast
             * @enum {string}
             */
            response_mode: "fast" | "full";
            /** Answer Budget Ms */
            answer_budget_ms?: number | null;
            /** Response Budget Ms */
            response_budget_ms?: number | null;
        };
        /** QueryOut */
        QueryOut: {
            /** Runs */
            runs: components["schemas"]["RunOut"][];
        };
        /** RerankerConnectionTestOut */
        RerankerConnectionTestOut: {
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Base Url */
            base_url: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Variant Id */
            variant_id: string;
            /** Experiment Id */
            experiment_id: string | null;
            /** Query */
            query: string;
            status: components["schemas"]["StageStatus"];
            /** Answer */
            answer: string;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Chunk Traces */
            chunk_traces: {
                [key: string]: unknown;
            }[];
            /** Timings */
            timings: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Runtime Profile Id */
            runtime_profile_id?: string | null;
            /** Document Ids */
            document_ids?: string[];
            /** Query Config */
            query_config?: {
                [key: string]: unknown;
            };
            /** Reranker Traces */
            reranker_traces?: {
                [key: string]: unknown;
            }[];
            /** Token Metadata */
            token_metadata?: {
                [key: string]: unknown;
            };
            /** Error Type */
            error_type?: string | null;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Total */
            total: number;
        };
        /** RuntimeHealthCheck */
        RuntimeHealthCheck: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "failed" | "skipped";
            /**
             * Severity
             * @default info
             * @enum {string}
             */
            severity: "info" | "warning" | "blocking";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detail */
            detail: string;
            /** Error Type */
            error_type?: string | null;
            /** Remediation */
            remediation?: string | null;
        };
        /** SettingsProfileIn */
        SettingsProfileIn: {
            /** Provider */
            provider: string;
            /** Llm Model */
            llm_model: string;
            /**
             * Llm Provider
             * @default openai_compatible
             * @constant
             */
            llm_provider: "openai_compatible";
            /** Llm Base Url */
            llm_base_url?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
            /**
             * Llm Timeout Ms
             * @default 10000
             */
            llm_timeout_ms: number;
            /** Llm Capabilities */
            llm_capabilities?: ("text" | "vision" | "reasoning")[];
            /** Embedding Model */
            embedding_model: string;
            /**
             * Storage Backend
             * @default postgres_pgvector_neo4j
             * @constant
             */
            storage_backend: "postgres_pgvector_neo4j";
            /**
             * Embedding Provider
             * @default vllm_openai
             * @constant
             */
            embedding_provider: "vllm_openai";
            /** Embedding Base Url */
            embedding_base_url?: string | null;
            /** Embedding Api Key */
            embedding_api_key?: string | null;
            /**
             * Embedding Timeout Ms
             * @default 10000
             */
            embedding_timeout_ms: number;
            /**
             * Embedding Dimensions
             * @default 1536
             */
            embedding_dimensions: number;
            /**
             * Embedding Batch Size
             * @default 16
             */
            embedding_batch_size: number;
            /**
             * Embedding Tls Verify
             * @default true
             */
            embedding_tls_verify: boolean;
            /**
             * Mineru Enabled
             * @default false
             */
            mineru_enabled: boolean;
            /** Mineru Base Url */
            mineru_base_url?: string | null;
            /**
             * Mineru Timeout Ms
             * @default 14400000
             */
            mineru_timeout_ms: number;
            /**
             * Mineru Poll Interval Ms
             * @default 1000
             */
            mineru_poll_interval_ms: number;
            /**
             * Mineru Require Hpc
             * @default true
             */
            mineru_require_hpc: boolean;
            /**
             * Mineru Backend
             * @default pipeline
             */
            mineru_backend: string;
            /**
             * Mineru Device
             * @default cuda:0
             */
            mineru_device: string;
            /** Mineru Lang */
            mineru_lang?: string | null;
            /**
             * Mineru Formula
             * @default true
             */
            mineru_formula: boolean;
            /**
             * Mineru Table
             * @default true
             */
            mineru_table: boolean;
            /** Mineru Source */
            mineru_source?: string | null;
            /**
             * Mineru Max Concurrent Files
             * @default 1
             */
            mineru_max_concurrent_files: number;
            /**
             * Runtime Mode
             * @default runtime
             * @constant
             */
            runtime_mode: "runtime";
            /** Vision Model */
            vision_model?: string | null;
            /** Vision Base Url */
            vision_base_url?: string | null;
            /** Vision Api Key */
            vision_api_key?: string | null;
            /**
             * Vision Timeout Ms
             * @default 10000
             */
            vision_timeout_ms: number;
            /**
             * Reranker Provider
             * @default disabled
             * @enum {string}
             */
            reranker_provider: "disabled" | "cohere_compatible" | "jina_compatible" | "generic_http" | "llm";
            /**
             * Reranker Fallback Provider
             * @default disabled
             * @enum {string}
             */
            reranker_fallback_provider: "disabled" | "llm";
            /** Reranker Model */
            reranker_model?: string | null;
            /** Reranker Base Url */
            reranker_base_url?: string | null;
            /** Reranker Api Key */
            reranker_api_key?: string | null;
            /**
             * Reranker Timeout Ms
             * @default 10000
             */
            reranker_timeout_ms: number;
            /**
             * Pgvector Schema
             * @default public
             */
            pgvector_schema: string;
            /**
             * Pgvector Table Prefix
             * @default ragstudio
             */
            pgvector_table_prefix: string;
            /** Neo4J Uri */
            neo4j_uri?: string | null;
            /** Neo4J Username */
            neo4j_username?: string | null;
            /** Neo4J Password */
            neo4j_password?: string | null;
            /**
             * Parser
             * @default mineru
             */
            parser: string;
            /**
             * Parse Method
             * @default auto
             */
            parse_method: string;
            /**
             * Chunk Token Size
             * @default 1200
             */
            chunk_token_size: number;
            /**
             * Chunk Overlap Token Size
             * @default 100
             */
            chunk_overlap_token_size: number;
            /**
             * Enable Image Processing
             * @default true
             */
            enable_image_processing: boolean;
            /**
             * Enable Table Processing
             * @default true
             */
            enable_table_processing: boolean;
            /**
             * Enable Equation Processing
             * @default true
             */
            enable_equation_processing: boolean;
            /**
             * Context Window
             * @default 1
             */
            context_window: number;
            /**
             * Context Mode
             * @default page
             */
            context_mode: string;
            /**
             * Max Context Tokens
             * @default 2000
             */
            max_context_tokens: number;
            /**
             * Include Headers
             * @default true
             */
            include_headers: boolean;
            /**
             * Include Captions
             * @default true
             */
            include_captions: boolean;
            /**
             * Query Mode
             * @default mix
             * @enum {string}
             */
            query_mode: "mix" | "hybrid" | "local" | "global" | "naive";
            /**
             * Top K
             * @default 40
             */
            top_k: number;
            /**
             * Chunk Top K
             * @default 20
             */
            chunk_top_k: number;
            /**
             * Enable Rerank
             * @default true
             */
            enable_rerank: boolean;
            /**
             * Cosine Better Than Threshold
             * @default 0.2
             */
            cosine_better_than_threshold: number;
            /**
             * Max Total Tokens
             * @default 30000
             */
            max_total_tokens: number;
            /**
             * Max Entity Tokens
             * @default 6000
             */
            max_entity_tokens: number;
            /**
             * Max Relation Tokens
             * @default 8000
             */
            max_relation_tokens: number;
            /**
             * Enable Llm Cache
             * @default true
             */
            enable_llm_cache: boolean;
            /**
             * Enable Llm Cache For Entity Extract
             * @default true
             */
            enable_llm_cache_for_entity_extract: boolean;
            /**
             * Llm Model Max Async
             * @default 4
             */
            llm_model_max_async: number;
            /**
             * Embedding Func Max Async
             * @default 8
             */
            embedding_func_max_async: number;
            /**
             * Max Parallel Insert
             * @default 2
             */
            max_parallel_insert: number;
        };
        /** SettingsProfileOut */
        SettingsProfileOut: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Llm Model */
            llm_model: string;
            /**
             * Llm Provider
             * @constant
             */
            llm_provider: "openai_compatible";
            /** Llm Base Url */
            llm_base_url: string | null;
            /** Has Llm Api Key */
            has_llm_api_key: boolean;
            /** Llm Timeout Ms */
            llm_timeout_ms: number;
            /** Llm Capabilities */
            llm_capabilities: ("text" | "vision" | "reasoning")[];
            /** Embedding Model */
            embedding_model: string;
            /**
             * Storage Backend
             * @constant
             */
            storage_backend: "postgres_pgvector_neo4j";
            /**
             * Embedding Provider
             * @constant
             */
            embedding_provider: "vllm_openai";
            /** Embedding Base Url */
            embedding_base_url: string | null;
            /** Has Embedding Api Key */
            has_embedding_api_key: boolean;
            /** Embedding Timeout Ms */
            embedding_timeout_ms: number;
            /** Embedding Dimensions */
            embedding_dimensions: number;
            /** Embedding Batch Size */
            embedding_batch_size: number;
            /** Embedding Tls Verify */
            embedding_tls_verify: boolean;
            /** Mineru Enabled */
            mineru_enabled: boolean;
            /** Mineru Base Url */
            mineru_base_url: string | null;
            /** Mineru Timeout Ms */
            mineru_timeout_ms: number;
            /** Mineru Poll Interval Ms */
            mineru_poll_interval_ms: number;
            /** Mineru Require Hpc */
            mineru_require_hpc: boolean;
            /** Mineru Backend */
            mineru_backend: string;
            /** Mineru Device */
            mineru_device: string;
            /** Mineru Lang */
            mineru_lang: string | null;
            /** Mineru Formula */
            mineru_formula: boolean;
            /** Mineru Table */
            mineru_table: boolean;
            /** Mineru Source */
            mineru_source: string | null;
            /** Mineru Max Concurrent Files */
            mineru_max_concurrent_files: number;
            /**
             * Runtime Mode
             * @constant
             */
            runtime_mode: "runtime";
            /** Vision Model */
            vision_model: string | null;
            /** Vision Base Url */
            vision_base_url: string | null;
            /** Has Vision Api Key */
            has_vision_api_key: boolean;
            /** Vision Timeout Ms */
            vision_timeout_ms: number;
            /**
             * Reranker Provider
             * @enum {string}
             */
            reranker_provider: "disabled" | "cohere_compatible" | "jina_compatible" | "generic_http" | "llm";
            /**
             * Reranker Fallback Provider
             * @enum {string}
             */
            reranker_fallback_provider: "disabled" | "llm";
            /** Reranker Model */
            reranker_model: string | null;
            /** Reranker Base Url */
            reranker_base_url: string | null;
            /** Has Reranker Api Key */
            has_reranker_api_key: boolean;
            /** Reranker Timeout Ms */
            reranker_timeout_ms: number;
            /** Pgvector Schema */
            pgvector_schema: string;
            /** Pgvector Table Prefix */
            pgvector_table_prefix: string;
            /** Neo4J Uri */
            neo4j_uri: string | null;
            /** Neo4J Username */
            neo4j_username: string | null;
            /** Has Neo4J Password */
            has_neo4j_password: boolean;
            /** Parser */
            parser: string;
            /** Parse Method */
            parse_method: string;
            /** Chunk Token Size */
            chunk_token_size: number;
            /** Chunk Overlap Token Size */
            chunk_overlap_token_size: number;
            /** Enable Image Processing */
            enable_image_processing: boolean;
            /** Enable Table Processing */
            enable_table_processing: boolean;
            /** Enable Equation Processing */
            enable_equation_processing: boolean;
            /** Context Window */
            context_window: number;
            /** Context Mode */
            context_mode: string;
            /** Max Context Tokens */
            max_context_tokens: number;
            /** Include Headers */
            include_headers: boolean;
            /** Include Captions */
            include_captions: boolean;
            /**
             * Query Mode
             * @enum {string}
             */
            query_mode: "mix" | "hybrid" | "local" | "global" | "naive";
            /** Top K */
            top_k: number;
            /** Chunk Top K */
            chunk_top_k: number;
            /** Enable Rerank */
            enable_rerank: boolean;
            /** Cosine Better Than Threshold */
            cosine_better_than_threshold: number;
            /** Max Total Tokens */
            max_total_tokens: number;
            /** Max Entity Tokens */
            max_entity_tokens: number;
            /** Max Relation Tokens */
            max_relation_tokens: number;
            /** Enable Llm Cache */
            enable_llm_cache: boolean;
            /** Enable Llm Cache For Entity Extract */
            enable_llm_cache_for_entity_extract: boolean;
            /** Llm Model Max Async */
            llm_model_max_async: number;
            /** Embedding Func Max Async */
            embedding_func_max_async: number;
            /** Max Parallel Insert */
            max_parallel_insert: number;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "not_configured" | "ready" | "running" | "succeeded" | "failed" | "unsupported";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantIn */
        VariantIn: {
            /** Name */
            name: string;
            /**
             * Preset
             * @enum {string}
             */
            preset: "balanced" | "precise" | "broad" | "fast";
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** VariantOut */
        VariantOut: {
            /** Name */
            name: string;
            /**
             * Preset
             * @enum {string}
             */
            preset: "balanced" | "precise" | "broad" | "fast";
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
        };
        /** VariantPage */
        VariantPage: {
            /** Items */
            items: components["schemas"]["VariantOut"][];
            /** Total */
            total: number;
        };
        /** VariantUpdate */
        VariantUpdate: {
            /** Name */
            name: string;
            /**
             * Preset
             * @enum {string}
             */
            preset: "balanced" | "precise" | "broad" | "fast";
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_default_settings_api_settings_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProfileOut"];
                };
            };
        };
    };
    put_default_settings_api_settings_default_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_provider_preview_api_settings_default_sync_provider_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSyncPreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSyncPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_embedding_settings_api_settings_default_test_embedding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_settings_api_settings_default_test_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_reranker_settings_api_settings_default_test_reranker_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankerConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_mineru_settings_api_settings_default_test_mineru_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinerUConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variants_api_variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantPage"];
                };
            };
        };
    };
    create_variant_api_variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variant_api_variants__variant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_variants__variant_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_variant_api_variants__variant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_api_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexDocumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rematerialize_document_graph_api_documents__document_id__graph_rematerialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_domain_profiles_api_domain_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainProfileListOut"];
                };
            };
        };
    };
    get_reference_json_example_api_domain_profiles_reference_json_example_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    suggest_domain_metadata_api_domain_profiles_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_suggest_domain_metadata_api_domain_profiles_suggest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainMetadataSuggestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_domain_profile_api_domain_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_chunks_api_chunks_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkSearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
        };
    };
    job_quality_warnings_api_jobs__job_id__quality_warnings_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQualityWarningsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fix_job_quality_warnings_api_jobs__job_id__quality_warnings_fix_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQualityWarningRepairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_evaluation_set_api_evaluation_sets_import_post: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_evaluation_set_api_evaluation_sets_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_sets_api_evaluation_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetPage"];
                };
            };
        };
    };
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPage"];
                };
            };
        };
    };
    create_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_api_optimizer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_for_experiment_api_optimizer__experiment_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
        };
    };
    get_diagnostics_api_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOut"];
                };
            };
        };
    };
}
